---
parser: babel-eslint

parserOptions:
    ecmaVersion: 2018
    sourceType: module
    ecmaFeatures:
        impliedStrict: true
        jsx: true
    flowtype:
        onlyFilesWithFlowAnnotation: false

extends:
    - '@lectrum/eslint-config-core'
    - 'prettier'

plugins:
    - 'prettier'

rules:
    indent: [2, 4, SwitchCase: 1]
    arrow-spacing: [2, { before: true, after: true }]
    lines-around-comment:
        [
            2,
            {
                beforeBlockComment: true,
                afterBlockComment: false,
                beforeLineComment: true,
                afterLineComment: false,
            },
        ]
    prettier/prettier:
        - error
